

#include "win_def.h"
#include <windows.h>

JSRuntime * (*WIN_JS_NewRuntime)();
JSContext * (*WIN_JS_NewContext)(JSRuntime *rt);
void (*WIN_JS_SetRuntimeInfo)(JSRuntime *rt, const char *info);
void (*WIN_JS_SetMemoryLimit)(JSRuntime *rt, size_t limit);
void (*WIN_JS_SetGCThreshold)(JSRuntime *rt, size_t gc_threshold);
void (*WIN_JS_SetMaxStackSize)(JSRuntime *rt, size_t stack_size);
void (*WIN_JS_UpdateStackTop)(JSRuntime *rt);
JSRuntime *(*WIN_JS_NewRuntime2)(const JSMallocFunctions *mf, void *opaque);
void (*WIN_JS_FreeRuntime)(JSRuntime *rt);
void *(*WIN_JS_GetRuntimeOpaque)(JSRuntime *rt);
void (*WIN_JS_SetRuntimeOpaque)(JSRuntime *rt, void *opaque);
void (*WIN_JS_MarkValue)(JSRuntime *rt, JSValueConst val, JS_MarkFunc *mark_func);
void (*WIN_JS_RunGC)(JSRuntime *rt);
JS_BOOL (*WIN_JS_IsLiveObject)(JSRuntime *rt, JSValueConst obj);
JSContext *(*WIN_JS_NewContext)(JSRuntime *rt);
void (*WIN_JS_FreeContext)(JSContext *s);
JSContext *(*WIN_JS_DupContext)(JSContext *ctx);
void *(*WIN_JS_GetContextOpaque)(JSContext *ctx);
void (*WIN_JS_SetContextOpaque)(JSContext *ctx, void *opaque);
JSRuntime *(*WIN_JS_GetRuntime)(JSContext *ctx);
void (*WIN_JS_SetClassProto)(JSContext *ctx, JSClassID class_id, JSValue obj);
JSValue (*WIN_JS_GetClassProto)(JSContext *ctx, JSClassID class_id);
JSContext *(*WIN_JS_NewContextRaw)(JSRuntime *rt);
void (*WIN_JS_AddIntrinsicBaseObjects)(JSContext *ctx);
void (*WIN_JS_AddIntrinsicDate)(JSContext *ctx);
void (*WIN_JS_AddIntrinsicEval)(JSContext *ctx);
void (*WIN_JS_AddIntrinsicStringNormalize)(JSContext *ctx);
void (*WIN_JS_AddIntrinsicRegExpCompiler)(JSContext *ctx);
void (*WIN_JS_AddIntrinsicRegExp)(JSContext *ctx);
void (*WIN_JS_AddIntrinsicJSON)(JSContext *ctx);
void (*WIN_JS_AddIntrinsicProxy)(JSContext *ctx);
void (*WIN_JS_AddIntrinsicMapSet)(JSContext *ctx);
void (*WIN_JS_AddIntrinsicTypedArrays)(JSContext *ctx);
void (*WIN_JS_AddIntrinsicPromise)(JSContext *ctx);
void (*WIN_JS_AddIntrinsicBigInt)(JSContext *ctx);
void (*WIN_JS_AddIntrinsicBigFloat)(JSContext *ctx);
void (*WIN_JS_AddIntrinsicBigDecimal)(JSContext *ctx);
void (*WIN_JS_AddIntrinsicOperators)(JSContext *ctx);
void (*WIN_JS_EnableBignumExt)(JSContext *ctx, JS_BOOL enable);
JSValue (*WIN_js_string_codePointRange)(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv);
void *(*WIN_js_malloc_rt)(JSRuntime *rt, size_t size);
void (*WIN_js_free_rt)(JSRuntime *rt, void *ptr);
void *(*WIN_js_realloc_rt)(JSRuntime *rt, void *ptr, size_t size);
size_t (*WIN_js_malloc_usable_size_rt)(JSRuntime *rt, const void *ptr);
void *(*WIN_js_mallocz_rt)(JSRuntime *rt, size_t size);
void *(*WIN_js_malloc)(JSContext *ctx, size_t size);
void (*WIN_js_free)(JSContext *ctx, void *ptr);
void *(*WIN_js_realloc)(JSContext *ctx, void *ptr, size_t size);
size_t (*WIN_js_malloc_usable_size)(JSContext *ctx, const void *ptr);
void *(*WIN_js_realloc2)(JSContext *ctx, void *ptr, size_t size, size_t *pslack);
void *(*WIN_js_mallocz)(JSContext *ctx, size_t size);
char *(*WIN_js_strdup)(JSContext *ctx, const char *str);
char *(*WIN_js_strndup)(JSContext *ctx, const char *s, size_t n);
void (*WIN_JS_ComputeMemoryUsage)(JSRuntime *rt, JSMemoryUsage *s);
void (*WIN_JS_DumpMemoryUsage)(FILE *fp, const JSMemoryUsage *s, JSRuntime *rt);
JSAtom (*WIN_JS_NewAtomLen)(JSContext *ctx, const char *str, size_t len);
JSAtom (*WIN_JS_NewAtom)(JSContext *ctx, const char *str);
JSAtom (*WIN_JS_NewAtomUInt32)(JSContext *ctx, uint32_t n);
JSAtom (*WIN_JS_DupAtom)(JSContext *ctx, JSAtom v);
void (*WIN_JS_FreeAtom)(JSContext *ctx, JSAtom v);
void (*WIN_JS_FreeAtomRT)(JSRuntime *rt, JSAtom v);
JSValue (*WIN_JS_AtomToValue)(JSContext *ctx, JSAtom atom);
JSValue (*WIN_JS_AtomToString)(JSContext *ctx, JSAtom atom);
const char *(*WIN_JS_AtomToCString)(JSContext *ctx, JSAtom atom);
JSAtom (*WIN_JS_ValueToAtom)(JSContext *ctx, JSValueConst val);
JSClassID (*WIN_JS_NewClassID)(JSClassID *pclass_id);
int (*WIN_JS_NewClass)(JSRuntime *rt, JSClassID class_id, const JSClassDef *class_def);
int (*WIN_JS_IsRegisteredClass)(JSRuntime *rt, JSClassID class_id);
JSValue (*WIN_JS_NewBigInt64)(JSContext *ctx, int64_t v);
JSValue (*WIN_JS_NewBigUint64)(JSContext *ctx, uint64_t v);
JSValue (*WIN_JS_Throw)(JSContext *ctx, JSValue obj);
JSValue (*WIN_JS_GetException)(JSContext *ctx);
JS_BOOL (*WIN_JS_IsError)(JSContext *ctx, JSValueConst val);
void (*WIN_JS_ResetUncatchableError)(JSContext *ctx);
JSValue (*WIN_JS_NewError)(JSContext *ctx);
JSValue __js_printf_like(2, 3) (*WIN_JS_ThrowSyntaxError)(JSContext *ctx, const char *fmt, ...);
JSValue __js_printf_like(2, 3) (*WIN_JS_ThrowTypeError)(JSContext *ctx, const char *fmt, ...);
JSValue __js_printf_like(2, 3) (*WIN_JS_ThrowReferenceError)(JSContext *ctx, const char *fmt, ...);
JSValue __js_printf_like(2, 3) (*WIN_JS_ThrowRangeError)(JSContext *ctx, const char *fmt, ...);
JSValue __js_printf_like(2, 3) (*WIN_JS_ThrowInternalError)(JSContext *ctx, const char *fmt, ...);
JSValue (*WIN_JS_ThrowOutOfMemory)(JSContext *ctx);
void (*WIN___JS_FreeValue)(JSContext *ctx, JSValue v);
void (*WIN___JS_FreeValueRT)(JSRuntime *rt, JSValue v);
int (*WIN_JS_ToBool)(JSContext *ctx, JSValueConst val); /* return -1 for JS_EXCEPTION */
int (*WIN_JS_ToInt32)(JSContext *ctx, int32_t *pres, JSValueConst val);
int (*WIN_JS_ToInt64)(JSContext *ctx, int64_t *pres, JSValueConst val);
int (*WIN_JS_ToIndex)(JSContext *ctx, uint64_t *plen, JSValueConst val);
int (*WIN_JS_ToFloat64)(JSContext *ctx, double *pres, JSValueConst val);
int (*WIN_JS_ToBigInt64)(JSContext *ctx, int64_t *pres, JSValueConst val);
int (*WIN_JS_ToInt64Ext)(JSContext *ctx, int64_t *pres, JSValueConst val);
JSValue (*WIN_JS_NewStringLen)(JSContext *ctx, const char *str1, size_t len1);
JSValue (*WIN_JS_NewString)(JSContext *ctx, const char *str);
JSValue (*WIN_JS_NewAtomString)(JSContext *ctx, const char *str);
JSValue (*WIN_JS_ToString)(JSContext *ctx, JSValueConst val);
JSValue (*WIN_JS_ToPropertyKey)(JSContext *ctx, JSValueConst val);
const char *(*WIN_JS_ToCStringLen2)(JSContext *ctx, size_t *plen, JSValueConst val1, JS_BOOL cesu8);
void (*WIN_JS_FreeCString)(JSContext *ctx, const char *ptr);
JSValue (*WIN_JS_NewObjectProtoClass)(JSContext *ctx, JSValueConst proto, JSClassID class_id);
JSValue (*WIN_JS_NewObjectClass)(JSContext *ctx, int class_id);
JSValue (*WIN_JS_NewObjectProto)(JSContext *ctx, JSValueConst proto);
JSValue (*WIN_JS_NewObject)(JSContext *ctx);
JS_BOOL (*WIN_JS_IsFunction)(JSContext* ctx, JSValueConst val);
JS_BOOL (*WIN_JS_IsConstructor)(JSContext* ctx, JSValueConst val);
JS_BOOL (*WIN_JS_SetConstructorBit)(JSContext *ctx, JSValueConst func_obj, JS_BOOL val);
JSValue (*WIN_JS_NewArray)(JSContext *ctx);
int (*WIN_JS_IsArray)(JSContext *ctx, JSValueConst val);
JSValue (*WIN_JS_GetPropertyInternal)(JSContext *ctx, JSValueConst obj,JSAtom prop, JSValueConst receiver,JS_BOOL throw_ref_error);
JSValue (*WIN_JS_GetPropertyStr)(JSContext *ctx, JSValueConst this_obj,const char *prop);
JSValue (*WIN_JS_GetPropertyUint32)(JSContext *ctx, JSValueConst this_obj,uint32_t idx);
int (*WIN_JS_SetPropertyInternal)(JSContext *ctx, JSValueConst this_obj,JSAtom prop, JSValue val,int flags);
int (*WIN_JS_SetPropertyUint32)(JSContext *ctx, JSValueConst this_obj,uint32_t idx, JSValue val);
int (*WIN_JS_SetPropertyInt64)(JSContext *ctx, JSValueConst this_obj,int64_t idx, JSValue val);
int (*WIN_JS_SetPropertyStr)(JSContext *ctx, JSValueConst this_obj, const char *prop, JSValue val);
int (*WIN_JS_HasProperty)(JSContext *ctx, JSValueConst this_obj, JSAtom prop);
int (*WIN_JS_IsExtensible)(JSContext *ctx, JSValueConst obj);
int (*WIN_JS_PreventExtensions)(JSContext *ctx, JSValueConst obj);
int (*WIN_JS_DeleteProperty)(JSContext *ctx, JSValueConst obj, JSAtom prop, int flags);
int (*WIN_JS_SetPrototype)(JSContext *ctx, JSValueConst obj, JSValueConst proto_val);
JSValue (*WIN_JS_GetPrototype)(JSContext *ctx, JSValueConst val);
int (*WIN_JS_GetOwnPropertyNames)(JSContext *ctx, JSPropertyEnum **ptab, uint32_t *plen, JSValueConst obj, int flags);
int (*WIN_JS_GetOwnProperty)(JSContext *ctx, JSPropertyDescriptor *desc, JSValueConst obj, JSAtom prop);
JSValue (*WIN_JS_Call)(JSContext *ctx, JSValueConst func_obj, JSValueConst this_obj, int argc, JSValueConst *argv);
JSValue (*WIN_JS_Invoke)(JSContext *ctx, JSValueConst this_val, JSAtom atom, int argc, JSValueConst *argv);
JSValue (*WIN_JS_CallConstructor)(JSContext *ctx, JSValueConst func_obj, int argc, JSValueConst *argv);
JSValue (*WIN_JS_CallConstructor2)(JSContext *ctx, JSValueConst func_obj,JSValueConst new_target, int argc, JSValueConst *argv);
JS_BOOL (*WIN_JS_DetectModule)(const char *input, size_t input_len);
JSValue (*WIN_JS_Eval)(JSContext *ctx, const char *input, size_t input_len,const char *filename, int eval_flags);
JSValue (*WIN_JS_EvalThis)(JSContext *ctx, JSValueConst this_obj, const char *input, size_t input_len, const char *filename, int eval_flags);
JSValue (*WIN_JS_GetGlobalObject)(JSContext *ctx);
int (*WIN_JS_IsInstanceOf)(JSContext *ctx, JSValueConst val, JSValueConst obj);
int (*WIN_JS_DefineProperty)(JSContext *ctx, JSValueConst this_obj, JSAtom prop, JSValueConst val, JSValueConst getter, JSValueConst setter, int flags);
int (*WIN_JS_DefinePropertyValue)(JSContext *ctx, JSValueConst this_obj,JSAtom prop, JSValue val, int flags);
int (*WIN_JS_DefinePropertyValueUint32)(JSContext *ctx, JSValueConst this_obj,uint32_t idx, JSValue val, int flags);
int (*WIN_JS_DefinePropertyValueStr)(JSContext *ctx, JSValueConst this_obj,  const char *prop, JSValue val, int flags);
int (*WIN_JS_DefinePropertyGetSet)(JSContext *ctx, JSValueConst this_obj, JSAtom prop, JSValue getter, JSValue setter,int flags);
void (*WIN_JS_SetOpaque)(JSValue obj, void *opaque);
void *(*WIN_JS_GetOpaque)(JSValueConst obj, JSClassID class_id);
void *(*WIN_JS_GetOpaque2)(JSContext *ctx, JSValueConst obj, JSClassID class_id);
JSValue (*WIN_JS_ParseJSON)(JSContext *ctx, const char *buf, size_t buf_len, const char *filename);
JSValue (*WIN_JS_ParseJSON2)(JSContext *ctx, const char *buf, size_t buf_len, const char *filename, int flags);
JSValue (*WIN_JS_JSONStringify)(JSContext *ctx, JSValueConst obj, JSValueConst replacer, JSValueConst space0);
JSValue (*WIN_JS_NewArrayBuffer)(JSContext *ctx, uint8_t *buf, size_t len, JSFreeArrayBufferDataFunc *free_func, void *opaque, JS_BOOL is_shared);
JSValue (*WIN_JS_NewArrayBufferCopy)(JSContext *ctx, const uint8_t *buf, size_t len);
void (*WIN_JS_DetachArrayBuffer)(JSContext *ctx, JSValueConst obj);
uint8_t *(*WIN_JS_GetArrayBuffer)(JSContext *ctx, size_t *psize, JSValueConst obj);
JSValue (*WIN_JS_GetTypedArrayBuffer)(JSContext *ctx, JSValueConst obj, size_t *pbyte_offset, size_t *pbyte_length, size_t *pbytes_per_element);
void (*WIN_JS_SetSharedArrayBufferFunctions)(JSRuntime *rt, const JSSharedArrayBufferFunctions *sf);
JSValue (*WIN_JS_NewPromiseCapability)(JSContext *ctx, JSValue *resolving_funcs);
void (*WIN_JS_SetHostPromiseRejectionTracker)(JSRuntime *rt, JSHostPromiseRejectionTracker *cb, void *opaque);
void (*WIN_JS_SetInterruptHandler)(JSRuntime *rt, JSInterruptHandler *cb, void *opaque);
void (*WIN_JS_SetCanBlock)(JSRuntime *rt, JS_BOOL can_block);
void (*WIN_JS_SetIsHTMLDDA)(JSContext *ctx, JSValueConst obj);
void (*WIN_JS_SetModuleLoaderFunc)(JSRuntime *rt, JSModuleNormalizeFunc *module_normalize, JSModuleLoaderFunc *module_loader, void *opaque);
JSValue (*WIN_JS_GetImportMeta)(JSContext *ctx, JSModuleDef *m);
JSAtom (*WIN_JS_GetModuleName)(JSContext *ctx, JSModuleDef *m);
int (*WIN_JS_EnqueueJob)(JSContext *ctx, JSJobFunc *job_func, int argc, JSValueConst *argv);
JS_BOOL (*WIN_JS_IsJobPending)(JSRuntime *rt);
int (*WIN_JS_ExecutePendingJob)(JSRuntime *rt, JSContext **pctx);
uint8_t *(*WIN_JS_WriteObject)(JSContext *ctx, size_t *psize, JSValueConst obj, int flags);
uint8_t *(*WIN_JS_WriteObject2)(JSContext *ctx, size_t *psize, JSValueConst obj, int flags, uint8_t ***psab_tab, size_t *psab_tab_len);
JSValue (*WIN_JS_ReadObject)(JSContext *ctx, const uint8_t *buf, size_t buf_len, int flags);
JSValue (*WIN_JS_EvalFunction)(JSContext *ctx, JSValue fun_obj);
int (*WIN_JS_ResolveModule)(JSContext *ctx, JSValueConst obj);
JSAtom (*WIN_JS_GetScriptOrModuleName)(JSContext *ctx, int n_stack_levels);
JSModuleDef *(*WIN_JS_RunModule)(JSContext *ctx, const char *basename, const char *filename);
JSValue (*WIN_JS_NewCFunction2)(JSContext *ctx, JSCFunction *func, const char *name,int length, JSCFunctionEnum cproto, int magic);
JSValue (*WIN_JS_NewCFunctionData)(JSContext *ctx, JSCFunctionData *func, int length, int magic, int data_len,JSValueConst *data);
void (*WIN_JS_SetConstructor)(JSContext *ctx, JSValueConst func_obj, JSValueConst proto);
void (*WIN_JS_SetPropertyFunctionList)(JSContext *ctx, JSValueConst obj,const JSCFunctionListEntry *tab,int len);
JSModuleDef *(*WIN_JS_NewCModule)(JSContext *ctx, const char *name_str,  JSModuleInitFunc *func);
int (*WIN_JS_AddModuleExport)(JSContext *ctx, JSModuleDef *m, const char *name_str);
int (*WIN_JS_AddModuleExportList)(JSContext *ctx, JSModuleDef *m, const JSCFunctionListEntry *tab, int len);
int (*WIN_JS_SetModuleExport)(JSContext *ctx, JSModuleDef *m, const char *export_name, JSValue val);
int (*WIN_JS_SetModuleExportList)(JSContext *ctx, JSModuleDef *m, const JSCFunctionListEntry *tab, int len);


JSModuleDef *(*WIN_js_init_module_std)(JSContext *ctx, const char *module_name);
JSModuleDef *(*WIN_js_init_module_os)(JSContext *ctx, const char *module_name);
void (*WIN_js_std_add_helpers)(JSContext *ctx, int argc, char **argv);
void (*WIN_js_std_loop)(JSContext *ctx);
void (*WIN_js_std_init_handlers)(JSRuntime *rt);
void (*WIN_js_std_free_handlers)(JSRuntime *rt);
void (*WIN_js_std_dump_error)(JSContext *ctx);
uint8_t *(*WIN_js_load_file)(JSContext *ctx, size_t *pbuf_len, const char *filename);
int (*WIN_js_module_set_import_meta)(JSContext *ctx, JSValueConst func_val, JS_BOOL use_realpath, JS_BOOL is_main);
JSModuleDef *(*WIN_js_module_loader)(JSContext *ctx, const char *module_name, void *opaque);
void (*WIN_js_std_eval_binary)(JSContext *ctx, const uint8_t *buf, size_t buf_len, int flags);
void (*WIN_js_std_promise_rejection_tracker)(JSContext *ctx, JSValueConst promise, JSValueConst reason, JS_BOOL is_handled, void *opaque);
void (*WIN_js_std_set_worker_new_context_func)(JSContext *(*func)(JSRuntime *rt));

static HMODULE _jsc_hl;
static int load_ok = 0;

void win_jsc_fn_init(const char* const path){
    if(load_ok) return;

    _jsc_hl = LoadLibrary(path);

    WIN_JS_NewRuntime = (void*)(GetProcAddress(_jsc_hl, "JS_NewRuntime"));
    WIN_JS_NewContext = (void*)(GetProcAddress(_jsc_hl, "JS_NewContext"));
    WIN_JS_SetRuntimeInfo = (void*)(GetProcAddress(_jsc_hl, "JS_SetRuntimeInfo"));
    WIN_JS_SetMemoryLimit = (void*)(GetProcAddress(_jsc_hl, "JS_SetMemoryLimit"));
    WIN_JS_SetGCThreshold = (void*)(GetProcAddress(_jsc_hl, "JS_SetGCThreshold"));
    WIN_JS_SetMaxStackSize = (void*)(GetProcAddress(_jsc_hl, "JS_SetMaxStackSize"));
    WIN_JS_UpdateStackTop = (void*)(GetProcAddress(_jsc_hl, "JS_UpdateStackTop"));
    WIN_JS_NewRuntime2 = (void*)(GetProcAddress(_jsc_hl, "JS_NewRuntime2"));
    WIN_JS_FreeRuntime = (void*)(GetProcAddress(_jsc_hl, "JS_FreeRuntime"));
    WIN_JS_GetRuntimeOpaque = (void*)(GetProcAddress(_jsc_hl, "JS_GetRuntimeOpaque"));
    WIN_JS_SetRuntimeOpaque = (void*)(GetProcAddress(_jsc_hl, "JS_SetRuntimeOpaque"));
    WIN_JS_MarkValue = (void*)(GetProcAddress(_jsc_hl, "JS_MarkValue"));
    WIN_JS_RunGC = (void*)(GetProcAddress(_jsc_hl, "JS_RunGC"));
    WIN_JS_IsLiveObject = (void*)(GetProcAddress(_jsc_hl, "JS_IsLiveObject"));
    WIN_JS_NewContext = (void*)(GetProcAddress(_jsc_hl, "JS_NewContext"));
    WIN_JS_FreeContext = (void*)(GetProcAddress(_jsc_hl, "JS_FreeContext"));
    WIN_JS_DupContext = (void*)(GetProcAddress(_jsc_hl, "JS_DupContext"));
    WIN_JS_GetContextOpaque = (void*)(GetProcAddress(_jsc_hl, "JS_GetContextOpaque"));
    WIN_JS_SetContextOpaque = (void*)(GetProcAddress(_jsc_hl, "JS_SetContextOpaque"));
    WIN_JS_GetRuntime = (void*)(GetProcAddress(_jsc_hl, "JS_GetRuntime"));
    WIN_JS_SetClassProto = (void*)(GetProcAddress(_jsc_hl, "JS_SetClassProto"));
    WIN_JS_GetClassProto = (void*)(GetProcAddress(_jsc_hl, "JS_GetClassProto"));
    WIN_JS_NewContextRaw = (void*)(GetProcAddress(_jsc_hl, "JS_NewContextRaw"));
    WIN_JS_AddIntrinsicBaseObjects = (void*)(GetProcAddress(_jsc_hl, "JS_AddIntrinsicBaseObjects"));
    WIN_JS_AddIntrinsicDate = (void*)(GetProcAddress(_jsc_hl, "JS_AddIntrinsicDate"));
    WIN_JS_AddIntrinsicEval = (void*)(GetProcAddress(_jsc_hl, "JS_AddIntrinsicEval"));
    WIN_JS_AddIntrinsicStringNormalize = (void*)(GetProcAddress(_jsc_hl, "JS_AddIntrinsicStringNormalize"));
    WIN_JS_AddIntrinsicRegExpCompiler = (void*)(GetProcAddress(_jsc_hl, "JS_AddIntrinsicRegExpCompiler"));
    WIN_JS_AddIntrinsicRegExp = (void*)(GetProcAddress(_jsc_hl, "JS_AddIntrinsicRegExp"));
    WIN_JS_AddIntrinsicJSON = (void*)(GetProcAddress(_jsc_hl, "JS_AddIntrinsicJSON"));
    WIN_JS_AddIntrinsicProxy = (void*)(GetProcAddress(_jsc_hl, "JS_AddIntrinsicProxy"));
    WIN_JS_AddIntrinsicMapSet = (void*)(GetProcAddress(_jsc_hl, "JS_AddIntrinsicMapSet"));
    WIN_JS_AddIntrinsicTypedArrays = (void*)(GetProcAddress(_jsc_hl, "JS_AddIntrinsicTypedArrays"));
    WIN_JS_AddIntrinsicPromise = (void*)(GetProcAddress(_jsc_hl, "JS_AddIntrinsicPromise"));
    WIN_JS_AddIntrinsicBigInt = (void*)(GetProcAddress(_jsc_hl, "JS_AddIntrinsicBigInt"));
    WIN_JS_AddIntrinsicBigFloat = (void*)(GetProcAddress(_jsc_hl, "JS_AddIntrinsicBigFloat"));
    WIN_JS_AddIntrinsicBigDecimal = (void*)(GetProcAddress(_jsc_hl, "JS_AddIntrinsicBigDecimal"));
    WIN_JS_AddIntrinsicOperators = (void*)(GetProcAddress(_jsc_hl, "JS_AddIntrinsicOperators"));
    WIN_JS_EnableBignumExt = (void*)(GetProcAddress(_jsc_hl, "JS_EnableBignumExt"));
    WIN_js_string_codePointRange = (void*)(GetProcAddress(_jsc_hl, "js_string_codePointRange"));
    WIN_js_malloc_rt = (void*)(GetProcAddress(_jsc_hl, "js_malloc_rt"));
    WIN_js_free_rt = (void*)(GetProcAddress(_jsc_hl, "js_free_rt"));
    WIN_js_realloc_rt = (void*)(GetProcAddress(_jsc_hl, "js_realloc_rt"));
    WIN_js_malloc_usable_size_rt = (void*)(GetProcAddress(_jsc_hl, "js_malloc_usable_size_rt"));
    WIN_js_mallocz_rt = (void*)(GetProcAddress(_jsc_hl, "js_mallocz_rt"));
    WIN_js_malloc = (void*)(GetProcAddress(_jsc_hl, "js_malloc"));
    WIN_js_free = (void*)(GetProcAddress(_jsc_hl, "js_free"));
    WIN_js_realloc = (void*)(GetProcAddress(_jsc_hl, "js_realloc"));
    WIN_js_malloc_usable_size = (void*)(GetProcAddress(_jsc_hl, "js_malloc_usable_size"));
    WIN_js_realloc2 = (void*)(GetProcAddress(_jsc_hl, "js_realloc2"));
    WIN_js_mallocz = (void*)(GetProcAddress(_jsc_hl, "js_mallocz"));
    WIN_js_strdup = (void*)(GetProcAddress(_jsc_hl, "js_strdup"));
    WIN_js_strndup = (void*)(GetProcAddress(_jsc_hl, "js_strndup"));
    WIN_JS_ComputeMemoryUsage = (void*)(GetProcAddress(_jsc_hl, "JS_ComputeMemoryUsage"));
    WIN_JS_DumpMemoryUsage = (void*)(GetProcAddress(_jsc_hl, "JS_DumpMemoryUsage"));
    WIN_JS_NewAtomLen = (void*)(GetProcAddress(_jsc_hl, "JS_NewAtomLen"));
    WIN_JS_NewAtom = (void*)(GetProcAddress(_jsc_hl, "JS_NewAtom"));
    WIN_JS_NewAtomUInt32 = (void*)(GetProcAddress(_jsc_hl, "JS_NewAtomUInt32"));
    WIN_JS_DupAtom = (void*)(GetProcAddress(_jsc_hl, "JS_DupAtom"));
    WIN_JS_FreeAtom = (void*)(GetProcAddress(_jsc_hl, "JS_FreeAtom"));
    WIN_JS_FreeAtomRT = (void*)(GetProcAddress(_jsc_hl, "JS_FreeAtomRT"));
    WIN_JS_AtomToValue = (void*)(GetProcAddress(_jsc_hl, "JS_AtomToValue"));
    WIN_JS_AtomToString = (void*)(GetProcAddress(_jsc_hl, "JS_AtomToString"));
    WIN_JS_AtomToCString = (void*)(GetProcAddress(_jsc_hl, "JS_AtomToCString"));
    WIN_JS_ValueToAtom = (void*)(GetProcAddress(_jsc_hl, "JS_ValueToAtom"));
    WIN_JS_NewClassID = (void*)(GetProcAddress(_jsc_hl, "JS_NewClassID"));
    WIN_JS_NewClass = (void*)(GetProcAddress(_jsc_hl, "JS_NewClass"));
    WIN_JS_IsRegisteredClass = (void*)(GetProcAddress(_jsc_hl, "JS_IsRegisteredClass"));
    WIN_JS_NewBigInt64 = (void*)(GetProcAddress(_jsc_hl, "JS_NewBigInt64"));
    WIN_JS_NewBigUint64 = (void*)(GetProcAddress(_jsc_hl, "JS_NewBigUint64"));
    WIN_JS_Throw = (void*)(GetProcAddress(_jsc_hl, "JS_Throw"));
    WIN_JS_GetException = (void*)(GetProcAddress(_jsc_hl, "JS_GetException"));
    WIN_JS_IsError = (void*)(GetProcAddress(_jsc_hl, "JS_IsError"));
    WIN_JS_ResetUncatchableError = (void*)(GetProcAddress(_jsc_hl, "JS_ResetUncatchableError"));
    WIN_JS_NewError = (void*)(GetProcAddress(_jsc_hl, "JS_NewError"));
    WIN_JS_ThrowSyntaxError = (void*)(GetProcAddress(_jsc_hl, "JS_ThrowSyntaxError"));
    WIN_JS_ThrowTypeError = (void*)(GetProcAddress(_jsc_hl, "JS_ThrowTypeError"));
    WIN_JS_ThrowReferenceError = (void*)(GetProcAddress(_jsc_hl, "JS_ThrowReferenceError"));
    WIN_JS_ThrowRangeError = (void*)(GetProcAddress(_jsc_hl, "JS_ThrowRangeError"));
    WIN_JS_ThrowInternalError = (void*)(GetProcAddress(_jsc_hl, "JS_ThrowInternalError"));
    WIN_JS_ThrowOutOfMemory = (void*)(GetProcAddress(_jsc_hl, "JS_ThrowOutOfMemory"));
    WIN___JS_FreeValue = (void*)(GetProcAddress(_jsc_hl, "__JS_FreeValue"));
    WIN___JS_FreeValueRT = (void*)(GetProcAddress(_jsc_hl, "__JS_FreeValueRT"));
    WIN_JS_ToBool = (void*)(GetProcAddress(_jsc_hl, "JS_ToBool"));
    WIN_JS_ToInt32 = (void*)(GetProcAddress(_jsc_hl, "JS_ToInt32"));
    WIN_JS_ToInt64 = (void*)(GetProcAddress(_jsc_hl, "JS_ToInt64"));
    WIN_JS_ToIndex = (void*)(GetProcAddress(_jsc_hl, "JS_ToIndex"));
    WIN_JS_ToFloat64 = (void*)(GetProcAddress(_jsc_hl, "JS_ToFloat64"));
    WIN_JS_ToBigInt64 = (void*)(GetProcAddress(_jsc_hl, "JS_ToBigInt64"));
    WIN_JS_ToInt64Ext = (void*)(GetProcAddress(_jsc_hl, "JS_ToInt64Ext"));
    WIN_JS_NewStringLen = (void*)(GetProcAddress(_jsc_hl, "JS_NewStringLen"));
    WIN_JS_NewString = (void*)(GetProcAddress(_jsc_hl, "JS_NewString"));
    WIN_JS_NewAtomString = (void*)(GetProcAddress(_jsc_hl, "JS_NewAtomString"));
    WIN_JS_ToString = (void*)(GetProcAddress(_jsc_hl, "JS_ToString"));
    WIN_JS_ToPropertyKey = (void*)(GetProcAddress(_jsc_hl, "JS_ToPropertyKey"));
    WIN_JS_ToCStringLen2 = (void*)(GetProcAddress(_jsc_hl, "JS_ToCStringLen2"));
    WIN_JS_FreeCString = (void*)(GetProcAddress(_jsc_hl, "JS_FreeCString"));
    WIN_JS_NewObjectProtoClass = (void*)(GetProcAddress(_jsc_hl, "JS_NewObjectProtoClass"));
    WIN_JS_NewObjectClass = (void*)(GetProcAddress(_jsc_hl, "JS_NewObjectClass"));
    WIN_JS_NewObjectProto = (void*)(GetProcAddress(_jsc_hl, "JS_NewObjectProto"));
    WIN_JS_NewObject = (void*)(GetProcAddress(_jsc_hl, "JS_NewObject"));
    WIN_JS_IsFunction = (void*)(GetProcAddress(_jsc_hl, "JS_IsFunction"));
    WIN_JS_IsConstructor = (void*)(GetProcAddress(_jsc_hl, "JS_IsConstructor"));
    WIN_JS_SetConstructorBit = (void*)(GetProcAddress(_jsc_hl, "JS_SetConstructorBit"));
    WIN_JS_NewArray = (void*)(GetProcAddress(_jsc_hl, "JS_NewArray"));
    WIN_JS_IsArray = (void*)(GetProcAddress(_jsc_hl, "JS_IsArray"));
    WIN_JS_GetPropertyInternal = (void*)(GetProcAddress(_jsc_hl, "JS_GetPropertyInternal"));
    WIN_JS_GetPropertyStr = (void*)(GetProcAddress(_jsc_hl, "JS_GetPropertyStr"));
    WIN_JS_GetPropertyUint32 = (void*)(GetProcAddress(_jsc_hl, "JS_GetPropertyUint32"));
    WIN_JS_SetPropertyInternal = (void*)(GetProcAddress(_jsc_hl, "JS_SetPropertyInternal"));
    WIN_JS_SetPropertyUint32 = (void*)(GetProcAddress(_jsc_hl, "JS_SetPropertyUint32"));
    WIN_JS_SetPropertyInt64 = (void*)(GetProcAddress(_jsc_hl, "JS_SetPropertyInt64"));
    WIN_JS_SetPropertyStr = (void*)(GetProcAddress(_jsc_hl, "JS_SetPropertyStr"));
    WIN_JS_HasProperty = (void*)(GetProcAddress(_jsc_hl, "JS_HasProperty"));
    WIN_JS_IsExtensible = (void*)(GetProcAddress(_jsc_hl, "JS_IsExtensible"));
    WIN_JS_PreventExtensions = (void*)(GetProcAddress(_jsc_hl, "JS_PreventExtensions"));
    WIN_JS_DeleteProperty = (void*)(GetProcAddress(_jsc_hl, "JS_DeleteProperty"));
    WIN_JS_SetPrototype = (void*)(GetProcAddress(_jsc_hl, "JS_SetPrototype"));
    WIN_JS_GetPrototype = (void*)(GetProcAddress(_jsc_hl, "JS_GetPrototype"));
    WIN_JS_GetOwnPropertyNames = (void*)(GetProcAddress(_jsc_hl, "JS_GetOwnPropertyNames"));
    WIN_JS_GetOwnProperty = (void*)(GetProcAddress(_jsc_hl, "JS_GetOwnProperty"));
    WIN_JS_Call = (void*)(GetProcAddress(_jsc_hl, "JS_Call"));
    WIN_JS_Invoke = (void*)(GetProcAddress(_jsc_hl, "JS_Invoke"));
    WIN_JS_CallConstructor = (void*)(GetProcAddress(_jsc_hl, "JS_CallConstructor"));
    WIN_JS_CallConstructor2 = (void*)(GetProcAddress(_jsc_hl, "JS_CallConstructor2"));
    WIN_JS_DetectModule = (void*)(GetProcAddress(_jsc_hl, "JS_DetectModule"));
    WIN_JS_Eval = (void*)(GetProcAddress(_jsc_hl, "JS_Eval"));
    WIN_JS_EvalThis = (void*)(GetProcAddress(_jsc_hl, "JS_EvalThis"));
    WIN_JS_GetGlobalObject = (void*)(GetProcAddress(_jsc_hl, "JS_GetGlobalObject"));
    WIN_JS_IsInstanceOf = (void*)(GetProcAddress(_jsc_hl, "JS_IsInstanceOf"));
    WIN_JS_DefineProperty = (void*)(GetProcAddress(_jsc_hl, "JS_DefineProperty"));
    WIN_JS_DefinePropertyValue = (void*)(GetProcAddress(_jsc_hl, "JS_DefinePropertyValue"));
    WIN_JS_DefinePropertyValueUint32 = (void*)(GetProcAddress(_jsc_hl, "JS_DefinePropertyValueUint32"));
    WIN_JS_DefinePropertyValueStr = (void*)(GetProcAddress(_jsc_hl, "JS_DefinePropertyValueStr"));
    WIN_JS_DefinePropertyGetSet = (void*)(GetProcAddress(_jsc_hl, "JS_DefinePropertyGetSet"));
    WIN_JS_SetOpaque = (void*)(GetProcAddress(_jsc_hl, "JS_SetOpaque"));
    WIN_JS_GetOpaque = (void*)(GetProcAddress(_jsc_hl, "JS_GetOpaque"));
    WIN_JS_GetOpaque2 = (void*)(GetProcAddress(_jsc_hl, "JS_GetOpaque2"));
    WIN_JS_ParseJSON = (void*)(GetProcAddress(_jsc_hl, "JS_ParseJSON"));
    WIN_JS_ParseJSON2 = (void*)(GetProcAddress(_jsc_hl, "JS_ParseJSON2"));
    WIN_JS_JSONStringify = (void*)(GetProcAddress(_jsc_hl, "JS_JSONStringify"));
    WIN_JS_NewArrayBuffer = (void*)(GetProcAddress(_jsc_hl, "JS_NewArrayBuffer"));
    WIN_JS_NewArrayBufferCopy = (void*)(GetProcAddress(_jsc_hl, "JS_NewArrayBufferCopy"));
    WIN_JS_DetachArrayBuffer = (void*)(GetProcAddress(_jsc_hl, "JS_DetachArrayBuffer"));
    WIN_JS_GetArrayBuffer = (void*)(GetProcAddress(_jsc_hl, "JS_GetArrayBuffer"));
    WIN_JS_GetTypedArrayBuffer = (void*)(GetProcAddress(_jsc_hl, "JS_GetTypedArrayBuffer"));
    WIN_JS_SetSharedArrayBufferFunctions = (void*)(GetProcAddress(_jsc_hl, "JS_SetSharedArrayBufferFunctions"));
    WIN_JS_NewPromiseCapability = (void*)(GetProcAddress(_jsc_hl, "JS_NewPromiseCapability"));
    WIN_JS_SetHostPromiseRejectionTracker = (void*)(GetProcAddress(_jsc_hl, "JS_SetHostPromiseRejectionTracker"));
    WIN_JS_SetInterruptHandler = (void*)(GetProcAddress(_jsc_hl, "JS_SetInterruptHandler"));
    WIN_JS_SetCanBlock = (void*)(GetProcAddress(_jsc_hl, "JS_SetCanBlock"));
    WIN_JS_SetIsHTMLDDA = (void*)(GetProcAddress(_jsc_hl, "JS_SetIsHTMLDDA"));
    WIN_JS_SetModuleLoaderFunc = (void*)(GetProcAddress(_jsc_hl, "JS_SetModuleLoaderFunc"));
    WIN_JS_GetImportMeta = (void*)(GetProcAddress(_jsc_hl, "JS_GetImportMeta"));
    WIN_JS_GetModuleName = (void*)(GetProcAddress(_jsc_hl, "JS_GetModuleName"));
    WIN_JS_EnqueueJob = (void*)(GetProcAddress(_jsc_hl, "JS_EnqueueJob"));
    WIN_JS_IsJobPending = (void*)(GetProcAddress(_jsc_hl, "JS_IsJobPending"));
    WIN_JS_ExecutePendingJob = (void*)(GetProcAddress(_jsc_hl, "JS_ExecutePendingJob"));
    WIN_JS_WriteObject = (void*)(GetProcAddress(_jsc_hl, "JS_WriteObject"));
    WIN_JS_WriteObject2 = (void*)(GetProcAddress(_jsc_hl, "JS_WriteObject2"));
    WIN_JS_ReadObject = (void*)(GetProcAddress(_jsc_hl, "JS_ReadObject"));
    WIN_JS_EvalFunction = (void*)(GetProcAddress(_jsc_hl, "JS_EvalFunction"));
    WIN_JS_ResolveModule = (void*)(GetProcAddress(_jsc_hl, "JS_ResolveModule"));
    WIN_JS_GetScriptOrModuleName = (void*)(GetProcAddress(_jsc_hl, "JS_GetScriptOrModuleName"));
    WIN_JS_RunModule = (void*)(GetProcAddress(_jsc_hl, "JS_RunModule"));
    WIN_JS_NewCFunction2 = (void*)(GetProcAddress(_jsc_hl, "JS_NewCFunction2"));
    WIN_JS_NewCFunctionData = (void*)(GetProcAddress(_jsc_hl, "JS_NewCFunctionData"));
    WIN_JS_SetConstructor = (void*)(GetProcAddress(_jsc_hl, "JS_SetConstructor"));
    WIN_JS_SetPropertyFunctionList = (void*)(GetProcAddress(_jsc_hl, "JS_SetPropertyFunctionList"));
    WIN_JS_NewCModule = (void*)(GetProcAddress(_jsc_hl, "JS_NewCModule"));
    WIN_JS_AddModuleExport = (void*)(GetProcAddress(_jsc_hl, "JS_AddModuleExport"));
    WIN_JS_AddModuleExportList = (void*)(GetProcAddress(_jsc_hl, "JS_AddModuleExportList"));
    WIN_JS_SetModuleExport = (void*)(GetProcAddress(_jsc_hl, "JS_SetModuleExport"));
    WIN_JS_SetModuleExportList = (void*)(GetProcAddress(_jsc_hl, "JS_SetModuleExportList"));
    WIN_js_init_module_std = (void*)(GetProcAddress(_jsc_hl, "js_init_module_std"));
    WIN_js_init_module_os = (void*)(GetProcAddress(_jsc_hl, "js_init_module_os"));
    WIN_js_std_add_helpers = (void*)(GetProcAddress(_jsc_hl, "js_std_add_helpers"));
    WIN_js_std_loop = (void*)(GetProcAddress(_jsc_hl, "js_std_loop"));
    WIN_js_std_init_handlers = (void*)(GetProcAddress(_jsc_hl, "js_std_init_handlers"));
    WIN_js_std_free_handlers = (void*)(GetProcAddress(_jsc_hl, "js_std_free_handlers"));
    WIN_js_std_dump_error = (void*)(GetProcAddress(_jsc_hl, "js_std_dump_error"));
    WIN_js_load_file = (void*)(GetProcAddress(_jsc_hl, "js_load_file"));
    WIN_js_module_set_import_meta = (void*)(GetProcAddress(_jsc_hl, "js_module_set_import_meta"));
    WIN_js_module_loader = (void*)(GetProcAddress(_jsc_hl, "js_module_loader"));
    WIN_js_std_eval_binary = (void*)(GetProcAddress(_jsc_hl, "js_std_eval_binary"));
    WIN_js_std_promise_rejection_tracker = (void*)(GetProcAddress(_jsc_hl, "js_std_promise_rejection_tracker"));
    WIN_js_std_set_worker_new_context_func = (void*)(GetProcAddress(_jsc_hl, "js_std_set_worker_new_context_func"));

    load_ok = 1;
}

int win_jsc_fn_free(){
    if (!load_ok) return 0;

    return FreeLibrary(_jsc_hl);
}